.MODEL SMALL
.STACK
.DATA  
    CHAR DB ?   
    MSG_NUMBER DB 'The input is a number. $'
    MSG_CHARACTER DB 'The input is a character.'
    MSG_SPECIAL DB 'The input is a special character.$'
.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX


    MOV AH, 01H
    INT 21H
    MOV CHAR, AL

  
    CMP CHAR, '0'
    JB CHECK_CHARACTER
    CMP CHAR, '9'
    JA CHECK_CHARACTER
    MOV DX, OFFSET MSG_NUMBER
    JMP DISPLAY_MESSAGE

CHECK_CHARACTER:
    CMP CHAR, 'A'
    JB CHECK_SPECIAL
    CMP CHAR, 'Z'
    JA CHECK_LOWER_CASE
    MOV DX, OFFSET MSG_CHARACTER
    JMP DISPLAY_MESSAGE

CHECK_LOWER_CASE:
    CMP CHAR, 'a'
    JB CHECK_SPECIAL
    CMP CHAR, 'z'
    JA CHECK_SPECIAL
    MOV DX, OFFSET MSG_CHARACTER
    JMP DISPLAY_MESSAGE

CHECK_SPECIAL:
    MOV DX, OFFSET MSG_SPECIAL

DISPLAY_MESSAGE:
    MOV AH, 09H
    INT 21H

    MOV AH, 4CH
    INT 21H

MAIN ENDP
END MAIN



